### ISSUE TITLE
The data has removed from the website

### ISSUE THREAD

**Issue by zjw1990** [alicank/Translation-Augmented-LibriSpeech-Corpus#2]
Hi,  Alicank,

I find the link you have offered have been removed from the website. Could you update the resource? 

Thanks,
Cheers

**Comment by alicank** [comment]
Hi,

The dataset link is unavailable due to hacking attempts on the university platform hosting datasets.
It should become available in the upcoming days. However, do not hesitate to contact

anthony.hombiat@univ-grenoble-alpes.fr and contact-perscido@univ-grenoble-alpes.fr
in the meanwhile. They might share a temporary link for downloading the dataset.

Sorry for the inconvienance

Cheers
